server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/docai
    username: docai_user
    password: docai_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: c9c1b2f3e4a5d6b7c8a9e0f1d2c3b4a5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1
  expiration: 86400000 # 24 hours

rsa:
  # Đây là một test key, trong môi trường production nên sử dụng key an toàn hơn
  private-key-value: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCR7Kd8qcLhJl3q
    RBE0HgGhRgzVc6UpyBqH9FNwTQxZ4y0hPXOQXV0tFLYRdoGlN7gxhwk8zWHBhCxZ
    q8Kk/B35JYqOL8WEhjHhxWZGXfiBvR/S0AmwUGlzqxQWuZHGXKzDGXXRaZk5HKlL
    +nqJ7dXjGPHzfKzV7O0fQJw0+5Ks3LhGUZPQyj7Ui+yHNXfKz9Qp5wG5C0jZd1LP
    0QkqDLLjwHXm0SqhqQTgWaGgPYhI0WryXS1YXtn3iBcqD5IpLaO1BgfDhW1yJGQD
    1QcQ7VzHwXbGRf7dN8ZqDLGREBu6PYBhqPNGPFCGX9pQFvHEqGIHJqJBVPr8KcVK
    kB+qz1QfAgMBAAECggEABa0didGbQJHVvhGQC9kYE8PX3mLA0pFaQJSvYZzZ5FfS
    Hs3RPrFIUy4ULwH9I5DzLPrpXz6yGGZYqj7YGEwgGqJG8J+1CBZzRbotXrEVKZ4e
    TgIxZk5HxPVRvJcDGBUYEQ48XZIxyzQD0K3oLHjUC7TPjPUXzsz1dR3qGxCI1eRE
    1xZLvQGPBkpf+HpvZxKJ1IuqPPZjsKzxkYD1mGxLaYx8zE4zqhD+/OVNc8MtFYZr
    3PtXG5tvQoL7ZcyWi4wcGwEwYRTzqZF0XbwpqKLIkp1E4QRoI4B1aC+TGUIwDiQg
    5uqdrCUxm6UzKA5Ig+qSKL4qCwIR6TQVeGQFtVyQAQKBgQDFJC7n2jqBQI3zTKzX
    8qI2H7ZfGBuTkL2v1yEFKu4TBX5qwvOuwZy5PCbpKHRv0W7yNOuiY6XhQ8qTJaEX
    NhXzjDBtKR9u3jU5g8b8S9l+ib9d5Az8lZWHDOlC4qRYQzY6X1BX5PIh5wR5KZKA
    kV0GpBGrXWQV1r8L0JwBN7PwAQKBgQC9Vs0NyzQfR5y8jQhkttaTp0Lc4Rvytv6m
    4qLXyJ7zv7SJHqXX9UJ8qZZF0dzwMEcH3U5jxzGvNjY9AjVqFt4ypB+1w0JVHPnx
    lQZKEzCp3yLZOq0z9wqXEX/b7J0uQmLBUzWE8ALvybNXX7czXrvZLF7VyQxvgxF+
    fvZyTtQXHwKBgQCbvIEzXJGKvhBd1Ut0iWzKF8TqUC3UvHhL4t8wmxDGXNhvqz4O
    8yYEGhvxdgUKg8H5QJEFGQGGbZDVvqQqJ8XtZGmZFQhVHJCjHHMj9vppcPQHXmXG
    VyZZX0PjGc9EQK3GxU/4FPgDZxPB8BSd6DgzQNJHpUq+8MzL0wf4UgwAAQKBgCgJ
    9MOXPVJv1vWjJhWZxjEUPFZ6N1Zp0yqPWvQwkDVhGX/0jZK8B+JHb+BfYNGbpRVj
    fA0V8f3P1c7eZgNvNSI2zOZFVBHLhwKJC6zFUXGGwqyKZ7L7dOvLJKH/8XRNFyGt
    VGzHXXQQqKQh6qmZHkCwZEU3HUQaFpdjZkXNGXQtAoGAO6I8TuCmqBF0KyQXpGGe
    rzJjh9GjIO8pwHT3KJn1r3oPC5yXyyGiYJQxHUh1Eh7vC7bRBxhUz0JBvj3marHX
    h3ZQpHdJQYPPZwCj5mRdB/kK6DUjR4kJ3Kz1B6oPs5Dm3kvhsE+che+ARU2N2yEB
    TqXh1FWiWvQwFQELxUQ0JuE=
    -----END PRIVATE KEY-----

logging:
  level:
    org.springframework.web: INFO
    com.docai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
